# Generated by Django 4.2.2 on 2023-06-27 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table='blog',
        ),
    ]
