# Generated by Django 4.2.2 on 2023-06-27 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table=None,
        ),
    ]
