# Generated by Django 4.2.2 on 2023-06-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_created_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
